# Generated by Django 4.1.1 on 2022-09-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcoordinate',
            name='latitude',
            field=models.CharField(default=0.0, max_length=50),
        ),
        migrations.AddField(
            model_name='mapcoordinate',
            name='longitude',
            field=models.CharField(default=0.0, max_length=50),
        ),
    ]
