# Generated by Django 4.1.1 on 2022-10-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_mapcoordinate_latitude_mapcoordinate_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcoordinate',
            name='address',
            field=models.CharField(max_length=250, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='mapcoordinate',
            name='latitude',
            field=models.CharField(default=0.0, max_length=50, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='mapcoordinate',
            name='longitude',
            field=models.CharField(default=0.0, max_length=50, verbose_name='longitude'),
        ),
    ]
