# Generated by Django 4.1 on 2022-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('contact_preference', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=400)),
                ('property_type', models.CharField(choices=[('detached', 'Detached'), ('semidetached', 'Semidetached'), ('terraced', 'Terraced house'), ('apartment', 'Apartment'), ('other', 'Other')], default='detached', max_length=20)),
                ('property_type_other', models.CharField(blank=True, max_length=200)),
                ('construction_material', models.CharField(choices=[('bricks', 'Bricks/stone walls'), ('timber', 'Timber-framed walls'), ('other', 'Other')], default='bricks', max_length=20)),
                ('construction_material_other', models.CharField(blank=True, max_length=200)),
                ('number_of_people', models.IntegerField(default=1)),
                ('purpose_of_garden', models.CharField(choices=[('veg', 'Fruit and vegetable production'), ('plants', 'Gardening of ornamental plants'), ('natural recreation', 'Recreational activity benefiting from natural environment'), ('nonnatural recreation', 'Recreational activity without any relevance of natural environment'), ('storage', 'Storage space'), ('none', 'No specific use and limited leisure time spent in garden')], default='none', max_length=50)),
                ('area_for_growing_veg', models.CharField(choices=[('0', '<1 square meter'), ('1', '1-2 square meters'), ('2', '2-5 square meters'), ('5', '5-10 square meters'), ('10', '>10 square meters')], default='0', max_length=20)),
                ('average_gardening_hours', models.CharField(choices=[('0', '0-1 hours'), ('1', '1-2 hours'), ('2', '2-5 hours'), ('5', '5-10 hours'), ('10', '>10 hours')], default='0', max_length=20)),
                ('total_garden_area', models.CharField(choices=[('0', '<10 square meters'), ('10', '10-100 square meters'), ('100', '100-200 square meters'), ('200', '200-500 square meters'), ('500', '>500 square meters')], default='0', max_length=20)),
                ('sealed_garden_area', models.CharField(choices=[('0', '<10%'), ('10', '10-20%'), ('20', '20-50%'), ('50', '50-70%'), ('70', '70-100%')], default='0', max_length=20)),
                ('lawn_garden_area', models.CharField(choices=[('0', '<10%'), ('10', '10-20%'), ('20', '20-50%'), ('50', '50-70%'), ('70', '70-100%')], default='0', max_length=20)),
                ('lawn_type', models.CharField(choices=[('natural', 'Natural'), ('artificial', 'Artificial')], default='natural', max_length=20)),
                ('veg_garden_area', models.CharField(choices=[('0', '<10%'), ('10', '10-20%'), ('20', '20-50%'), ('50', '50-70%'), ('70', '70-100%')], default='0', max_length=20)),
                ('ornamental_plant_garden_area', models.CharField(choices=[('0', '<10%'), ('10', '10-20%'), ('20', '20-50%'), ('50', '50-70%'), ('70', '70-100%')], default='0', max_length=20)),
                ('natural_garden_area', models.CharField(choices=[('0', '<10%'), ('10', '10-20%'), ('20', '20-50%'), ('50', '50-70%'), ('70', '70-100%')], default='0', max_length=20)),
                ('veg_species', models.CharField(choices=[('lettuce', 'Lettuce'), ('spinach', 'Spinach'), ('herbs', 'Herbs'), ('carrots', 'Carrots'), ('potatoes', 'Potatoes'), ('onions', 'Onions'), ('beans', 'Beans'), ('tomatoes', 'Tomatoes'), ('apples', 'Apples'), ('pears', 'Pears'), ('cherries', 'Cherries'), ('strawberries', 'Strawberries'), ('other', 'Other')], default='lettuce', max_length=20)),
                ('raised_beds', models.BooleanField(default=False)),
                ('compost', models.CharField(choices=[('kitchen', 'I do compost kitchen waste'), ('garden', 'I do compost garden waste'), ('both', 'I do compost both kitchen and garden waste'), ('none', 'I do NOT compost any kitchen or garden waste')], default='kitchen', max_length=20)),
                ('commercial_compost', models.CharField(choices=[('3', '3+ times in the last year'), ('1', '1-3 times in the last year'), ('occasionally', 'Occasionally in the last 5 years'), ('never', 'Not in the last 5 years/never')], default='3', max_length=20)),
                ('commercial_fertiliser', models.CharField(choices=[('3', '3+ times in the last year'), ('1', '1-3 times in the last year'), ('occasionally', 'Occasionally in the last 5 years'), ('never', 'Not in the last 5 years/never')], default='3', max_length=20)),
                ('latest_compost_purchase', models.CharField(blank=True, max_length=200)),
                ('commercial_pesticide', models.CharField(choices=[('3', '3+ times in the last year'), ('1', '1-3 times in the last year'), ('occasionally', 'Occasionally in the last 5 years'), ('never', 'Not in the last 5 years/never')], default='3', max_length=20)),
                ('ornamental_plant_fertiliser', models.CharField(choices=[('3', '3+ times in the last year'), ('1', '1-3 times in the last year'), ('occasionally', 'Occasionally in the last 5 years'), ('never', 'Not in the last 5 years/never')], default='3', max_length=20)),
                ('ornamental_plant_pesticide', models.CharField(choices=[('3', '3+ times in the last year'), ('1', '1-3 times in the last year'), ('occasionally', 'Occasionally in the last 5 years'), ('never', 'Not in the last 5 years/never')], default='3', max_length=20)),
                ('soil_rubble', models.BooleanField(default=False)),
                ('soil_rubble_yes', models.CharField(blank=True, max_length=200)),
                ('bird_feeders', models.BooleanField(default=False)),
                ('pond', models.BooleanField(default=False)),
                ('house_sparrow', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('goldfinch', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('robin', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('wren', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('domestic_cat', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('red_fox', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('hedgehog', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('slow_worm', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('frog', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('mole', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('house_rat', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('bumblebee', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('ladybird', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('butterfly', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('seasonally', 'Seasonally'), ('yearly', 'Yearly'), ('never', 'Never')], default='daily', max_length=20)),
                ('other_notable_wildlife', models.CharField(blank=True, max_length=200)),
                ('sample_1_description', models.CharField(max_length=200)),
                ('sample_2_description', models.CharField(max_length=200)),
                ('sample_3_description', models.CharField(max_length=200)),
                ('sample_4_description', models.CharField(max_length=200)),
                ('sample_5_description', models.CharField(max_length=200)),
            ],
        ),
    ]
