# Generated by Django 4.1 on 2022-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_agreement_alter_participant_bird_feeders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
