# Generated by Django 4.1 on 2022-08-26 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participants', '0005_remove_participant_email_remove_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sample_label',
            field=models.CharField(default='38C94', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(default=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
