# Generated by Django 4.1 on 2022-08-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_participant_soil_sample_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='sample_label',
            field=models.CharField(default='A8394', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
