# Generated by Django 4.1 on 2022-09-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_alter_participant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='year_property_built',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
