# Generated by Django 4.1 on 2022-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_rename_sample_label_participant_participant_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='soil_sample_label',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
